CREATE TABLE users (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username text UNIQUE NOT NULL,
	passhash text NOT NULL
);

CREATE TABLE captures (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid uuid UNIQUE NOT NULL,
	url text NOT NULL,
	time_initiated timestamp with time zone NOT NULL,
	owner integer NOT NULL references users(id),
	public boolean NOT NULL
);

CREATE TABLE extracts (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid uuid UNIQUE NOT NULL,
	capture integer NOT NULL references captures(id),
	extractor text NOT NULL,
	success boolean NOT NULL,
	UNIQUE (capture, extractor)
);
